### PR TITLE
Commentlevel2

### PR DESCRIPTION
**Pull request by kms69**

### CODE REVIEW

**Comment by mohammadhsn** [comment]
Could you submit a PR for each exercise, please? You may either close this one and create a new PR or cleanup it.

**Comment by kms69** [comment]
for the last ex I made a new branch and just added one file to be commited and pushed. I dont know why is that happening and it drags previous file with itself.

**Comment by mohammadhsn** [comment]
There is a straight way:
- Update your master branch with the latest version of the upstream
- Create new branch **from the master branch**
- Commit and push your changes
- Create a pull request through for `upstream/master <- your new branch`

**Comment by kms69** [comment]
ok thanks .

**Pull request closed without merging**
