### PR TITLE
Level3 medium

### PR DESCRIPTION
**Pull request by mehdihasanpour**
Hi @mohammadhsn 
This PR is the resolve of medium level 3 exercise.

### CODE REVIEW

**Comment by mohammadhsn** [comment]
Great job.
What is the purpose of `PostProvider`? Does it solve a specific design problem?

**Comment by mehdihasanpour** [comment]
> Great job.
> What is the purpose of `PostProvider`? Does it solve a specific design problem?

thank you. 
I think if we want to save our posts on database or other resource we can change it easily this way. I think this method is D principle in SOLID. Dependency Inversion.

**Comment by mohammadhsn** [comment]
It is a true concern, what if we define a `PostRepositoryInterface` and implement it in `InMemoryPostRepository`? It seems the abstraction layer behind the repository observes the **dependency inversion** principle.

**Comment by mehdihasanpour** [comment]
> It is a true concern, what if we define a `PostRepositoryInterface` and implement it in `InMemoryPostRepository`? It seems the abstraction layer behind the repository observes the **dependency inversion** principle.

Thank you. I should work on it and try that

**Comment by mohammadhsn** [comment]
It's good enough for now, If you'd like to improve it, reopen the PR later

**Pull request closed without merging**
